export const industryOptions = [
  "Apparel, Accessories & Footwear",
  "Appliance Manufacturing",
  "Building Products & Furnishings",
  "E-Commerce",
  "Household & Personal Products",
  "Toys & Sporting Goods",
  "Multiline and Specialty Retailers & Distributors",
  "Construction Materials",
  "Coal Operations",
  "Oil & Gas - Exploration & Production",
  "Iron & Steel Producers",
  "Oil & Gas - Midstream",
  "Metals & Mining",
  "Oil & Gas - Refining & Marketing",
  "Oil & Gas - Services",
  "Insurance",
  "Asset Management & Custody Activities",
  "Commercial Banks",
  "Consumer Finance",
  "Security & Commodity Exchanges",
  "Investment Banking & Brokerage",
  "Mortgage Financing",
  "Alcoholic Beverages",
  "Agricultural Products",
  "Food Retailers & Distributors",
  "Meat, Poultry & Dairy",
  "Non-Alcoholic Beverages",
  "Processed Foods",
  "Restaurants",
  "Tobacco",
  "Biotechnology & Pharmaceuticals",
  "Healthcare Distributors",
  "Drug Retailers",
  "Health Care Delivery",
  "Managed Care",
  "Medical Equipment & Supplies",
  "Real Estate",
  "Engineering & Construction Services",
  "Electric Utilities & Power Generators",
  "Gas Utilities & Distributors",
  "Home Builders",
  "Waste Management",
  "Water Utilities & Services",
  "Biofuels",
  "Fuel Cells & Industrial Batteries",
  "Forestry Management",
  "Pulp & Paper Products",
  "Solar Technology & Project Developers",
  "Wind Technology & Project Developers",
  "Chemicals",
  "Aerospace & Défense",
  "Containers & Packaging",
  "Electrical & Electronic Equipment",
  "Industrial Machinery & Goods",
  "Advertising & Marketing",
  "Casinos & Gaming",
  "Education",
  "Hotels & Lodging",
  "Leisure Facilities",
  "Media & Entertainment",
  "Professional & Commercial Services",
  "Electronic Manufacturing Services & Original Design Manufacturing",
  "Hardware",
  "Internet Media & Services",
  "Semiconductors",
  "Software & IT Services",
  "Telecommunication Services",
  "Air Freight & Logistics",
  "Auto Parts",
  "Automobiles",
  "Cruise Lines",
  "Car Rental & Leasing",
  "Marine Transportation",
  "Rail Transportation",
  "Road Transportation",
];

export const accountMode = ["Live", "Demo"];

export const paymentStatusList = [
  { value: "paid", label: "Paid" },
  { value: "pending", label: "Pending" },
];
export const roleOptions = [
  { label: "Group Company Admin", value: "groupManager" },
  { label: "Company Admin", value: "companyAdmin" },
  { label: "Facility Manager", value: "facilityManager" },
];

// export const currencyOptions = [
//   { value: "usd", label: "USD - United States Dollar" },
//   { value: "inr", label: "INR - Indian Rupee" },
//   { value: "eur", label: "EUR - Euro" },
//   { value: "aed", label: "AED - United Arab Emirates Dirham" },
//   { value: "gbp", label: "GBP - British Pound" },
//   { value: "yen", label: "YEN - Japanese Yen" },
//   { value: "jpy", label: "JPY - Japanese Yen" },
//   { value: "aud", label: "AUD - Australian Dollar" },
//   { value: "cad", label: "CAD - Canadian Dollar" },
//   { value: "chf", label: "CHF - Swiss Franc" },
//   { value: "cny", label: "CNY - Chinese Yuan" },
//   { value: "nzd", label: "NZD - New Zealand Dollar" },
//   { value: "rub", label: "RUB - Russian Ruble" },
// ];

export const currencyOptions = [
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "USD", label: "USD - United States Dollar" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "AED", label: "AED - United Arab Emirates Dirham" },
  { value: "GBP", label: "GBP - British Pound Sterling" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "QAR", label: "QAR - Qatari Riyal" },
  // { value: "BHD", label: "BHD - Bahraini Dinar" },
  { value: "OMR", label: "OMR - Omani Rial" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
];

export const AdminRoles = [
  "Super Admin",
  "Management",
  "Finance And Accounts",
  "Tech Support",
  "Sales",
];

export const PaymentMethods = ["Stripe", "Razorpay"];

// +376 - Andorra
export const countries = [
  { code: "AD", label: "Andorra", phone: "376", pattern: /^\d{6}$/ },
  {
    code: "AE",
    label: "United Arab Emirates",
    phone: "971",
    pattern: /^[1-9]\d{8}$/,
  },
  { code: "AF", label: "Afghanistan", phone: "93", pattern: /^[1-9]\d{8}$/ },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    phone: "1-268",
    pattern: /^[2-9]\d{6}$/,
  },
  { code: "AI", label: "Anguilla", phone: "1-264", pattern: /^[2-9]\d{6}$/ },
  { code: "AL", label: "Albania", phone: "355", pattern: /^[1-9]\d{7,8}$/ },
  { code: "AM", label: "Armenia", phone: "374", pattern: /^[1-9]\d{7}$/ },
  { code: "AO", label: "Angola", phone: "244", pattern: /^[1-9]\d{8}$/ },
  { code: "AQ", label: "Antarctica", phone: "672", pattern: /^\d{6}$/ },
  { code: "AR", label: "Argentina", phone: "54", pattern: /^[1-9]\d{9}$/ },
  {
    code: "AS",
    label: "American Samoa",
    phone: "1-684",
    pattern: /^[2-9]\d{6}$/,
  },
  { code: "AT", label: "Austria", phone: "43", pattern: /^[1-9]\d{3,12}$/ },
  { code: "AU", label: "Australia", phone: "61", pattern: /^[1-9]\d{8}$/ },
  { code: "AW", label: "Aruba", phone: "297", pattern: /^[1-9]\d{6}$/ },
  {
    code: "AX",
    label: "Åland Islands",
    phone: "358",
    pattern: /^[1-9]\d{4,11}$/,
  },
  { code: "AZ", label: "Azerbaijan", phone: "994", pattern: /^[1-9]\d{8}$/ },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    phone: "387",
    pattern: /^[1-9]\d{7}$/,
  },
  { code: "BB", label: "Barbados", phone: "1-246", pattern: /^[2-9]\d{6}$/ },
  { code: "BD", label: "Bangladesh", phone: "880", pattern: /^[1-9]\d{9}$/ },
  { code: "BE", label: "Belgium", phone: "32", pattern: /^[1-9]\d{7,8}$/ },
  { code: "BF", label: "Burkina Faso", phone: "226", pattern: /^[1-9]\d{7}$/ },
  { code: "BG", label: "Bulgaria", phone: "359", pattern: /^[1-9]\d{8}$/ },
  { code: "BH", label: "Bahrain", phone: "973", pattern: /^[1-9]\d{7}$/ },
  { code: "BI", label: "Burundi", phone: "257", pattern: /^[1-9]\d{7}$/ },
  { code: "BJ", label: "Benin", phone: "229", pattern: /^[1-9]\d{7}$/ },
  {
    code: "BL",
    label: "Saint Barthélemy",
    phone: "590",
    pattern: /^[1-9]\d{8}$/,
  },
  { code: "BM", label: "Bermuda", phone: "1-441", pattern: /^[2-9]\d{6}$/ },
  {
    code: "BN",
    label: "Brunei",
    phone: "673",
    pattern: /^[1-9]\d{6}$/,
  },
  { code: "BO", label: "Bolivia", phone: "591", pattern: /^[1-9]\d{7}$/ },
  { code: "BR", label: "Brazil", phone: "55", pattern: /^[1-9]\d{9,10}$/ },
  { code: "BS", label: "Bahamas", phone: "1-242", pattern: /^[2-9]\d{6}$/ },
  { code: "BT", label: "Bhutan", phone: "975", pattern: /^[1-9]\d{7}$/ },
  { code: "BV", label: "Bouvet Island", phone: "47", pattern: /^[1-9]\d{7}$/ },
  { code: "BW", label: "Botswana", phone: "267", pattern: /^[1-9]\d{7}$/ },
  { code: "BY", label: "Belarus", phone: "375", pattern: /^[1-9]\d{8}$/ },
  { code: "BZ", label: "Belize", phone: "501", pattern: /^[1-9]\d{6}$/ },
  { code: "CA", label: "Canada", phone: "1", pattern: /^[2-9]\d{9}$/ },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    phone: "61",
    pattern: /^[1-9]\d{8}$/,
  },
  {
    code: "CD",
    label: "Congo, Democratic Republic",
    phone: "243",
    pattern: /^[1-9]\d{8}$/,
  },
  {
    code: "CF",
    label: "Central African Republic",
    phone: "236",
    pattern: /^[1-9]\d{7}$/,
  },
  { code: "CG", label: "Congo", phone: "242", pattern: /^[1-9]\d{7}$/ },
  { code: "CH", label: "Switzerland", phone: "41", pattern: /^[1-9]\d{8}$/ },
  { code: "CI", label: "Côte d'Ivoire", phone: "225", pattern: /^[1-9]\d{9}$/ },
  { code: "CK", label: "Cook Islands", phone: "682", pattern: /^[1-9]\d{4}$/ },
  { code: "CL", label: "Chile", phone: "56", pattern: /^[1-9]\d{8}$/ },
  { code: "CM", label: "Cameroon", phone: "237", pattern: /^[1-9]\d{7}$/ },
  { code: "CN", label: "China", phone: "86", pattern: /^1[3-9]\d{9}$/ },
  { code: "CO", label: "Colombia", phone: "57", pattern: /^[1-9]\d{9}$/ },
  { code: "CR", label: "Costa Rica", phone: "506", pattern: /^[1-9]\d{7}$/ },
  { code: "CU", label: "Cuba", phone: "53", pattern: /^[1-9]\d{7}$/ },
  { code: "CV", label: "Cape Verde", phone: "238", pattern: /^[1-9]\d{6}$/ },
  { code: "CW", label: "Curaçao", phone: "599", pattern: /^[1-9]\d{6}$/ },
  {
    code: "CX",
    label: "Christmas Island",
    phone: "61",
    pattern: /^[1-9]\d{8}$/,
  },
  { code: "CY", label: "Cyprus", phone: "357", pattern: /^[1-9]\d{7}$/ },
  {
    code: "CZ",
    label: "Czech Republic",
    phone: "420",
    pattern: /^[1-9]\d{8}$/,
  },
  { code: "DE", label: "Germany", phone: "49", pattern: /^[1-9]\d{4,14}$/ },
  { code: "DJ", label: "Djibouti", phone: "253", pattern: /^[1-9]\d{7}$/ },
  { code: "DK", label: "Denmark", phone: "45", pattern: /^[1-9]\d{7}$/ },
  { code: "DM", label: "Dominica", phone: "1-767", pattern: /^[2-9]\d{6}$/ },
  {
    code: "DO",
    label: "Dominican Republic",
    phone: "1-809",
    pattern: /^[2-9]\d{7}$/,
  },
  { code: "DU", label: "Dubai", phone: "971", pattern: /^[1-9]\d{8}$/ },
  { code: "DZ", label: "Algeria", phone: "213", pattern: /^[1-9]\d{8}$/ },
  { code: "EC", label: "Ecuador", phone: "593", pattern: /^[1-9]\d{8}$/ },
  { code: "EE", label: "Estonia", phone: "372", pattern: /^[1-9]\d{6,7}$/ },
  { code: "EG", label: "Egypt", phone: "20", pattern: /^[1-9]\d{9}$/ },
  {
    code: "EH",
    label: "Western Sahara",
    phone: "212",
    pattern: /^[1-9]\d{8}$/,
  },
  { code: "ER", label: "Eritrea", phone: "291", pattern: /^[1-9]\d{6}$/ },
  { code: "ES", label: "Spain", phone: "34", pattern: /^[1-9]\d{8}$/ },
  { code: "ET", label: "Ethiopia", phone: "251", pattern: /^[1-9]\d{8}$/ },
  { code: "FI", label: "Finland", phone: "358", pattern: /^[1-9]\d{4,11}$/ },
  { code: "FJ", label: "Fiji", phone: "679", pattern: /^[1-9]\d{6}$/ },
  {
    code: "FK",
    label: "Falkland Islands",
    phone: "500",
    pattern: /^[1-9]\d{4}$/,
  },
  { code: "FM", label: "Micronesia", phone: "691", pattern: /^[1-9]\d{6}$/ },
  { code: "FO", label: "Faroe Islands", phone: "298", pattern: /^[1-9]\d{5}$/ },
  { code: "FR", label: "France", phone: "33", pattern: /^[1-9]\d{8}$/ },
  { code: "GA", label: "Gabon", phone: "241", pattern: /^[1-9]\d{7}$/ },
  {
    code: "GB",
    label: "United Kingdom",
    phone: "44",
    pattern: /^[1-9]\d{9,10}$/,
  },
  { code: "GD", label: "Grenada", phone: "1-473", pattern: /^[2-9]\d{6}$/ },
  { code: "GE", label: "Georgia", phone: "995", pattern: /^[1-9]\d{8}$/ },
  { code: "GF", label: "French Guiana", phone: "594", pattern: /^[1-9]\d{8}$/ },
  { code: "GG", label: "Guernsey", phone: "44", pattern: /^[1-9]\d{9,10}$/ },
  { code: "GH", label: "Ghana", phone: "233", pattern: /^[1-9]\d{8}$/ },
  { code: "GI", label: "Gibraltar", phone: "350", pattern: /^[1-9]\d{7}$/ },
  { code: "GL", label: "Greenland", phone: "299", pattern: /^[1-9]\d{5}$/ },
  { code: "GM", label: "Gambia", phone: "220", pattern: /^[1-9]\d{6}$/ },
  { code: "GN", label: "Guinea", phone: "224", pattern: /^[1-9]\d{7}$/ },
  { code: "GP", label: "Guadeloupe", phone: "590", pattern: /^[1-9]\d{8}$/ },
  {
    code: "GQ",
    label: "Equatorial Guinea",
    phone: "240",
    pattern: /^[1-9]\d{7}$/,
  },
  { code: "GR", label: "Greece", phone: "30", pattern: /^[1-9]\d{9}$/ },
  { code: "GS", label: "South Georgia", phone: "500", pattern: /^[1-9]\d{4}$/ },
  { code: "GT", label: "Guatemala", phone: "502", pattern: /^[1-9]\d{7}$/ },
  { code: "GU", label: "Guam", phone: "1-671", pattern: /^[2-9]\d{6}$/ },
  { code: "GW", label: "Guinea-Bissau", phone: "245", pattern: /^[1-9]\d{7}$/ },
  { code: "GY", label: "Guyana", phone: "592", pattern: /^[1-9]\d{6}$/ },
  { code: "HK", label: "Hong Kong", phone: "852", pattern: /^[1-9]\d{7}$/ },
  { code: "HM", label: "Heard Island", phone: "672", pattern: /^\d{6}$/ },
  { code: "HN", label: "Honduras", phone: "504", pattern: /^[1-9]\d{7}$/ },
  { code: "HR", label: "Croatia", phone: "385", pattern: /^[1-9]\d{7,8}$/ },
  { code: "HT", label: "Haiti", phone: "509", pattern: /^[1-9]\d{7}$/ },
  { code: "HU", label: "Hungary", phone: "36", pattern: /^[1-9]\d{8}$/ },
  { code: "ID", label: "Indonesia", phone: "62", pattern: /^[1-9]\d{8,10}$/ },
  { code: "IE", label: "Ireland", phone: "353", pattern: /^[1-9]\d{8}$/ },
  { code: "IL", label: "Israel", phone: "972", pattern: /^[1-9]\d{8}$/ },
  { code: "IM", label: "Isle of Man", phone: "44", pattern: /^[1-9]\d{9,10}$/ },
  { code: "IN", label: "India", phone: "91", pattern: /^[6-9]\d{10}$/ },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    phone: "246",
    pattern: /^[1-9]\d{5}$/,
  },
  { code: "IQ", label: "Iraq", phone: "964", pattern: /^[1-9]\d{9}$/ },
  { code: "IR", label: "Iran", phone: "98", pattern: /^[1-9]\d{9}$/ },
  { code: "IS", label: "Iceland", phone: "354", pattern: /^[1-9]\d{6}$/ },
  { code: "IT", label: "Italy", phone: "39", pattern: /^[1-9]\d{8,9}$/ },
  { code: "JE", label: "Jersey", phone: "44", pattern: /^[1-9]\d{9,10}$/ },
  { code: "JM", label: "Jamaica", phone: "1-876", pattern: /^[2-9]\d{6}$/ },
  { code: "JO", label: "Jordan", phone: "962", pattern: /^[1-9]\d{8}$/ },
  { code: "JP", label: "Japan", phone: "81", pattern: /^[1-9]\d{8,9}$/ },
  { code: "KE", label: "Kenya", phone: "254", pattern: /^[1-9]\d{8}$/ },
  { code: "KG", label: "Kyrgyzstan", phone: "996", pattern: /^[1-9]\d{8}$/ },
  { code: "KH", label: "Cambodia", phone: "855", pattern: /^[1-9]\d{7,8}$/ },
  { code: "KI", label: "Kiribati", phone: "686", pattern: /^[1-9]\d{4}$/ },
  { code: "KM", label: "Comoros", phone: "269", pattern: /^[1-9]\d{6}$/ },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    phone: "1-869",
    pattern: /^[2-9]\d{6}$/,
  },
  { code: "KP", label: "North Korea", phone: "850", pattern: /^[1-9]\d{7}$/ },
  { code: "KR", label: "South Korea", phone: "82", pattern: /^[1-9]\d{8,9}$/ },
  { code: "KW", label: "Kuwait", phone: "965", pattern: /^[1-9]\d{7}$/ },
  {
    code: "KY",
    label: "Cayman Islands",
    phone: "1-345",
    pattern: /^[2-9]\d{6}$/,
  },
  { code: "KZ", label: "Kazakhstan", phone: "7", pattern: /^[1-9]\d{9}$/ },
  { code: "LA", label: "Laos", phone: "856", pattern: /^[1-9]\d{7,8}$/ },
  { code: "LB", label: "Lebanon", phone: "961", pattern: /^[1-9]\d{7}$/ },
  { code: "LC", label: "Saint Lucia", phone: "1-758", pattern: /^[2-9]\d{6}$/ },
  { code: "LI", label: "Liechtenstein", phone: "423", pattern: /^[1-9]\d{7}$/ },
  { code: "LK", label: "Sri Lanka", phone: "94", pattern: /^[1-9]\d{8}$/ },
  { code: "LR", label: "Liberia", phone: "231", pattern: /^[1-9]\d{7}$/ },
  { code: "LS", label: "Lesotho", phone: "266", pattern: /^[1-9]\d{7}$/ },
  { code: "LT", label: "Lithuania", phone: "370", pattern: /^[1-9]\d{7}$/ },
  { code: "LU", label: "Luxembourg", phone: "352", pattern: /^[1-9]\d{7}$/ },
  { code: "LV", label: "Latvia", phone: "371", pattern: /^[1-9]\d{7}$/ },
  { code: "LY", label: "Libya", phone: "218", pattern: /^[1-9]\d{8}$/ },
  { code: "MA", label: "Morocco", phone: "212", pattern: /^[1-9]\d{8}$/ },
  { code: "MC", label: "Monaco", phone: "377", pattern: /^[1-9]\d{7}$/ },
  { code: "MD", label: "Moldova", phone: "373", pattern: /^[1-9]\d{7}$/ },
  { code: "ME", label: "Montenegro", phone: "382", pattern: /^[1-9]\d{7}$/ },
  { code: "MF", label: "Saint Martin", phone: "590", pattern: /^[1-9]\d{8}$/ },
  { code: "MG", label: "Madagascar", phone: "261", pattern: /^[1-9]\d{8}$/ },
  {
    code: "MH",
    label: "Marshall Islands",
    phone: "692",
    pattern: /^[1-9]\d{6}$/,
  },
  {
    code: "MK",
    label: "North Macedonia",
    phone: "389",
    pattern: /^[1-9]\d{7}$/,
  },
  { code: "ML", label: "Mali", phone: "223", pattern: /^[1-9]\d{7}$/ },
  { code: "MM", label: "Myanmar", phone: "95", pattern: /^[1-9]\d{7,8}$/ },
  { code: "MN", label: "Mongolia", phone: "976", pattern: /^[1-9]\d{7}$/ },
  { code: "MO", label: "Macao", phone: "853", pattern: /^[1-9]\d{7}$/ },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    phone: "1-670",
    pattern: /^[2-9]\d{6}$/,
  },
  { code: "MQ", label: "Martinique", phone: "596", pattern: /^[1-9]\d{8}$/ },
  { code: "MR", label: "Mauritania", phone: "222", pattern: /^[1-9]\d{7}$/ },
  { code: "MS", label: "Montserrat", phone: "1-664", pattern: /^[2-9]\d{6}$/ },
  { code: "MT", label: "Malta", phone: "356", pattern: /^[1-9]\d{7}$/ },
  { code: "MU", label: "Mauritius", phone: "230", pattern: /^[1-9]\d{7}$/ },
  { code: "MV", label: "Maldives", phone: "960", pattern: /^[1-9]\d{6}$/ },
  { code: "MW", label: "Malawi", phone: "265", pattern: /^[1-9]\d{7}$/ },
  { code: "MX", label: "Mexico", phone: "52", pattern: /^[1-9]\d{9}$/ },
  { code: "MY", label: "Malaysia", phone: "60", pattern: /^[1-9]\d{8}$/ },
  { code: "MZ", label: "Mozambique", phone: "258", pattern: /^[1-9]\d{7}$/ },
  { code: "NA", label: "Namibia", phone: "264", pattern: /^[1-9]\d{7}$/ },
  { code: "NC", label: "New Caledonia", phone: "687", pattern: /^[1-9]\d{5}$/ },
  { code: "NE", label: "Niger", phone: "227", pattern: /^[1-9]\d{7}$/ },
  { code: "NF", label: "Norfolk Island", phone: "672", pattern: /^\d{6}$/ },
  { code: "NG", label: "Nigeria", phone: "234", pattern: /^[1-9]\d{9}$/ },
  { code: "NI", label: "Nicaragua", phone: "505", pattern: /^[1-9]\d{7}$/ },
  { code: "NL", label: "Netherlands", phone: "31", pattern: /^[1-9]\d{8}$/ },
  { code: "NO", label: "Norway", phone: "47", pattern: /^[1-9]\d{7}$/ },
  { code: "NP", label: "Nepal", phone: "977", pattern: /^[1-9]\d{9}$/ },
  { code: "NR", label: "Nauru", phone: "674", pattern: /^[1-9]\d{5}$/ },
  { code: "NU", label: "Niue", phone: "683", pattern: /^[1-9]\d{4}$/ },
  { code: "NZ", label: "New Zealand", phone: "64", pattern: /^[1-9]\d{7,9}$/ },
  { code: "OM", label: "Oman", phone: "968", pattern: /^[1-9]\d{7}$/ },
  { code: "PA", label: "Panama", phone: "507", pattern: /^[1-9]\d{7}$/ },
  { code: "PE", label: "Peru", phone: "51", pattern: /^[1-9]\d{8}$/ },
  {
    code: "PF",
    label: "French Polynesia",
    phone: "689",
    pattern: /^[1-9]\d{5}$/,
  },
  {
    code: "PG",
    label: "Papua New Guinea",
    phone: "675",
    pattern: /^[1-9]\d{6}$/,
  },
  { code: "PH", label: "Philippines", phone: "63", pattern: /^[1-9]\d{9}$/ },
  { code: "PK", label: "Pakistan", phone: "92", pattern: /^[1-9]\d{9}$/ },
  { code: "PL", label: "Poland", phone: "48", pattern: /^[1-9]\d{8}$/ },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    phone: "508",
    pattern: /^[1-9]\d{5}$/,
  },
  { code: "PN", label: "Pitcairn", phone: "870", pattern: /^[1-9]\d{8}$/ },
  { code: "PR", label: "Puerto Rico", phone: "1", pattern: /^[2-9]\d{9}$/ },
  { code: "PS", label: "Palestine", phone: "970", pattern: /^[1-9]\d{8}$/ },
  { code: "PT", label: "Portugal", phone: "351", pattern: /^[1-9]\d{8}$/ },
  { code: "PW", label: "Palau", phone: "680", pattern: /^[1-9]\d{6}$/ },
  { code: "PY", label: "Paraguay", phone: "595", pattern: /^[1-9]\d{7}$/ },
  { code: "QA", label: "Qatar", phone: "974", pattern: /^[1-9]\d{7}$/ },
  { code: "RE", label: "Réunion", phone: "262", pattern: /^[1-9]\d{8}$/ },
  { code: "RO", label: "Romania", phone: "40", pattern: /^[1-9]\d{8}$/ },
  { code: "RS", label: "Serbia", phone: "381", pattern: /^[1-9]\d{7,8}$/ },
  { code: "RU", label: "Russia", phone: "7", pattern: /^[1-9]\d{9}$/ },
  { code: "RW", label: "Rwanda", phone: "250", pattern: /^[1-9]\d{8}$/ },
  { code: "SA", label: "Saudi Arabia", phone: "966", pattern: /^[1-9]\d{8}$/ },
  {
    code: "SB",
    label: "Solomon Islands",
    phone: "677",
    pattern: /^[1-9]\d{5}$/,
  },
  { code: "SC", label: "Seychelles", phone: "248", pattern: /^[1-9]\d{5}$/ },
  { code: "SD", label: "Sudan", phone: "249", pattern: /^[1-9]\d{8}$/ },
  { code: "SE", label: "Sweden", phone: "46", pattern: /^[1-9]\d{7,8}$/ },
  { code: "SG", label: "Singapore", phone: "65", pattern: /^[1-9]\d{7}$/ },
  { code: "SH", label: "Saint Helena", phone: "290", pattern: /^[1-9]\d{4}$/ },
  { code: "SI", label: "Slovenia", phone: "386", pattern: /^[1-9]\d{7}$/ },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    phone: "47",
    pattern: /^[1-9]\d{7}$/,
  },
  { code: "SK", label: "Slovakia", phone: "421", pattern: /^[1-9]\d{8}$/ },
  { code: "SL", label: "Sierra Leone", phone: "232", pattern: /^[1-9]\d{7}$/ },
  { code: "SM", label: "San Marino", phone: "378", pattern: /^[1-9]\d{7}$/ },
  { code: "SN", label: "Senegal", phone: "221", pattern: /^[1-9]\d{7}$/ },
  { code: "SO", label: "Somalia", phone: "252", pattern: /^[1-9]\d{7}$/ },
  { code: "SR", label: "Suriname", phone: "597", pattern: /^[1-9]\d{6}$/ },
  { code: "SS", label: "South Sudan", phone: "211", pattern: /^[1-9]\d{8}$/ },
  {
    code: "ST",
    label: "São Tomé and Príncipe",
    phone: "239",
    pattern: /^[1-9]\d{6}$/,
  },
  { code: "SV", label: "El Salvador", phone: "503", pattern: /^[1-9]\d{7}$/ },
  {
    code: "SX",
    label: "Sint Maarten",
    phone: "1-721",
    pattern: /^[2-9]\d{6}$/,
  },
  { code: "SY", label: "Syria", phone: "963", pattern: /^[1-9]\d{8}$/ },
  { code: "SZ", label: "Eswatini", phone: "268", pattern: /^[1-9]\d{7}$/ },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    phone: "1-649",
    pattern: /^[2-9]\d{6}$/,
  },
  { code: "TD", label: "Chad", phone: "235", pattern: /^[1-9]\d{7}$/ },
  {
    code: "TF",
    label: "French Southern Territories",
    phone: "262",
    pattern: /^[1-9]\d{8}$/,
  },
  { code: "TG", label: "Togo", phone: "228", pattern: /^[1-9]\d{7}$/ },
  { code: "TH", label: "Thailand", phone: "66", pattern: /^[1-9]\d{8}$/ },
  { code: "TJ", label: "Tajikistan", phone: "992", pattern: /^[1-9]\d{8}$/ },
  { code: "TK", label: "Tokelau", phone: "690", pattern: /^[1-9]\d{4}$/ },
  { code: "TL", label: "Timor-Leste", phone: "670", pattern: /^[1-9]\d{7}$/ },
  { code: "TM", label: "Turkmenistan", phone: "993", pattern: /^[1-9]\d{7}$/ },
  { code: "TN", label: "Tunisia", phone: "216", pattern: /^[1-9]\d{7}$/ },
  { code: "TO", label: "Tonga", phone: "676", pattern: /^[1-9]\d{5}$/ },
  { code: "TR", label: "Turkey", phone: "90", pattern: /^[1-9]\d{9}$/ },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    phone: "1-868",
    pattern: /^[2-9]\d{6}$/,
  },
  { code: "TV", label: "Tuvalu", phone: "688", pattern: /^[1-9]\d{4}$/ },
  { code: "TW", label: "Taiwan", phone: "886", pattern: /^[1-9]\d{8}$/ },
  { code: "TZ", label: "Tanzania", phone: "255", pattern: /^[1-9]\d{8}$/ },
  { code: "UA", label: "Ukraine", phone: "380", pattern: /^[1-9]\d{8}$/ },
  { code: "UG", label: "Uganda", phone: "256", pattern: /^[1-9]\d{8}$/ },
  { code: "US", label: "United States", phone: "1", pattern: /^[2-9]\d{9}$/ },
  { code: "UY", label: "Uruguay", phone: "598", pattern: /^[1-9]\d{7}$/ },
  { code: "UZ", label: "Uzbekistan", phone: "998", pattern: /^[1-9]\d{8}$/ },
  { code: "VA", label: "Vatican City", phone: "379", pattern: /^[1-9]\d{7}$/ },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    phone: "1-784",
    pattern: /^[2-9]\d{6}$/,
  },
  { code: "VE", label: "Venezuela", phone: "58", pattern: /^[1-9]\d{9}$/ },
  {
    code: "VG",
    label: "British Virgin Islands",
    phone: "1-284",
    pattern: /^[2-9]\d{6}$/,
  },
  {
    code: "VI",
    label: "U.S. Virgin Islands",
    phone: "1-340",
    pattern: /^[2-9]\d{6}$/,
  },
  { code: "VN", label: "Vietnam", phone: "84", pattern: /^[1-9]\d{8,9}$/ },
  { code: "VU", label: "Vanuatu", phone: "678", pattern: /^[1-9]\d{5}$/ },
  {
    code: "WF",
    label: "Wallis and Futuna",
    phone: "681",
    pattern: /^[1-9]\d{5}$/,
  },
  { code: "WS", label: "Samoa", phone: "685", pattern: /^[1-9]\d{5}$/ },
  { code: "XK", label: "Kosovo", phone: "383", pattern: /^[1-9]\d{7}$/ },
  { code: "YE", label: "Yemen", phone: "967", pattern: /^[1-9]\d{8}$/ },
  { code: "YT", label: "Mayotte", phone: "262", pattern: /^[1-9]\d{8}$/ },
  { code: "ZA", label: "South Africa", phone: "27", pattern: /^[1-9]\d{8}$/ },
  { code: "ZM", label: "Zambia", phone: "260", pattern: /^[1-9]\d{8}$/ },
  { code: "ZW", label: "Zimbabwe", phone: "263", pattern: /^[1-9]\d{8}$/ },
];

export const newCounties = [
  "+376 - Andorra",
  "+971 - United Arab Emirates",
  "+93 - Afghanistan",
  "+1-268 - Antigua and Barbuda",
  "+1-264 - Anguilla",
  "+355 - Albania",
  "+374 - Armenia",
  "+244 - Angola",
  "+672 - Antarctica",
  "+54 - Argentina",
  "+1-684 - American Samoa",
  "+43 - Austria",
  "+61 - Australia",
  "+297 - Aruba",
  "+358 - Åland Islands",
  "+994 - Azerbaijan",
  "+387 - Bosnia and Herzegovina",
  "+1-246 - Barbados",
  "+880 - Bangladesh",
  "+32 - Belgium",
  "+226 - Burkina Faso",
  "+359 - Bulgaria",
  "+973 - Bahrain",
  "+257 - Burundi",
  "+229 - Benin",
  "+590 - Saint Barthélemy",
  "+1-441 - Bermuda",
  "+673 - Brunei",
  "+591 - Bolivia",
  "+55 - Brazil",
  "+1-242 - Bahamas",
  "+975 - Bhutan",
  "+47 - Bouvet Island",
  "+267 - Botswana",
  "+375 - Belarus",
  "+501 - Belize",
  "+1 - Canada",
  "+61 - Cocos (Keeling) Islands",
  "+243 - Congo, Democratic Republic",
  "+236 - Central African Republic",
  "+242 - Congo",
  "+41 - Switzerland",
  "+225 - Côte d'Ivoire",
  "+682 - Cook Islands",
  "+56 - Chile",
  "+237 - Cameroon",
  "+86 - China",
  "+57 - Colombia",
  "+506 - Costa Rica",
  "+53 - Cuba",
  "+238 - Cape Verde",
  "+599 - Curaçao",
  "+61 - Christmas Island",
  "+357 - Cyprus",
  "+420 - Czech Republic",
  "+49 - Germany",
  "+253 - Djibouti",
  "+45 - Denmark",
  "+1-767 - Dominica",
  "+1-809 - Dominican Republic",
  "+971 - Dubai",
  "+213 - Algeria",
  "+593 - Ecuador",
  "+372 - Estonia",
  "+20 - Egypt",
  "+212 - Western Sahara",
  "+291 - Eritrea",
  "+34 - Spain",
  "+251 - Ethiopia",
  "+358 - Finland",
  "+679 - Fiji",
  "+500 - Falkland Islands",
  "+691 - Micronesia",
  "+298 - Faroe Islands",
  "+33 - France",
  "+241 - Gabon",
  "+44 - United Kingdom",
  "+1-473 - Grenada",
  "+995 - Georgia",
  "+594 - French Guiana",
  "+44 - Guernsey",
  "+233 - Ghana",
  "+350 - Gibraltar",
  "+299 - Greenland",
  "+220 - Gambia",
  "+224 - Guinea",
  "+590 - Guadeloupe",
  "+240 - Equatorial Guinea",
  "+30 - Greece",
  "+500 - South Georgia",
  "+502 - Guatemala",
  "+1-671 - Guam",
  "+245 - Guinea-Bissau",
  "+592 - Guyana",
  "+852 - Hong Kong",
  "+672 - Heard Island",
  "+504 - Honduras",
  "+385 - Croatia",
  "+509 - Haiti",
  "+36 - Hungary",
  "+62 - Indonesia",
  "+353 - Ireland",
  "+972 - Israel",
  "+44 - Isle of Man",
  "+91 - India",
  "+246 - British Indian Ocean Territory",
  "+964 - Iraq",
  "+98 - Iran",
  "+354 - Iceland",
  "+39 - Italy",
  "+44 - Jersey",
  "+1-876 - Jamaica",
  "+962 - Jordan",
  "+81 - Japan",
  "+254 - Kenya",
  "+996 - Kyrgyzstan",
  "+855 - Cambodia",
  "+686 - Kiribati",
  "+269 - Comoros",
  "+1-869 - Saint Kitts and Nevis",
  "+850 - North Korea",
  "+82 - South Korea",
  "+965 - Kuwait",
  "+1-345 - Cayman Islands",
  "+7 - Kazakhstan",
  "+856 - Laos",
  "+961 - Lebanon",
  "+1-758 - Saint Lucia",
  "+423 - Liechtenstein",
  "+94 - Sri Lanka",
  "+231 - Liberia",
  "+266 - Lesotho",
  "+370 - Lithuania",
  "+352 - Luxembourg",
  "+371 - Latvia",
  "+218 - Libya",
  "+212 - Morocco",
  "+377 - Monaco",
  "+373 - Moldova",
  "+382 - Montenegro",
  "+590 - Saint Martin",
  "+261 - Madagascar",
  "+692 - Marshall Islands",
  "+389 - North Macedonia",
  "+223 - Mali",
  "+95 - Myanmar",
  "+976 - Mongolia",
  "+853 - Macao",
  "+1-670 - Northern Mariana Islands",
  "+596 - Martinique",
  "+222 - Mauritania",
  "+1-664 - Montserrat",
  "+356 - Malta",
  "+230 - Mauritius",
  "+960 - Maldives",
  "+265 - Malawi",
  "+52 - Mexico",
  "+60 - Malaysia",
  "+258 - Mozambique",
  "+264 - Namibia",
  "+687 - New Caledonia",
  "+227 - Niger",
  "+672 - Norfolk Island",
  "+234 - Nigeria",
  "+505 - Nicaragua",
  "+31 - Netherlands",
  "+47 - Norway",
  "+977 - Nepal",
  "+674 - Nauru",
  "+683 - Niue",
  "+64 - New Zealand",
  "+968 - Oman",
  "+507 - Panama",
  "+51 - Peru",
  "+689 - French Polynesia",
  "+675 - Papua New Guinea",
  "+63 - Philippines",
  "+92 - Pakistan",
  "+48 - Poland",
  "+508 - Saint Pierre and Miquelon",
  "+870 - Pitcairn",
  "+1 - Puerto Rico",
  "+970 - Palestine",
  "+351 - Portugal",
  "+680 - Palau",
  "+595 - Paraguay",
  "+974 - Qatar",
  "+262 - Réunion",
  "+40 - Romania",
  "+381 - Serbia",
  "+7 - Russia",
  "+250 - Rwanda",
  "+966 - Saudi Arabia",
  "+677 - Solomon Islands",
  "+248 - Seychelles",
  "+249 - Sudan",
  "+46 - Sweden",
  "+65 - Singapore",
  "+290 - Saint Helena",
  "+386 - Slovenia",
  "+47 - Svalbard and Jan Mayen",
  "+421 - Slovakia",
  "+232 - Sierra Leone",
  "+378 - San Marino",
  "+221 - Senegal",
  "+252 - Somalia",
  "+597 - Suriname",
  "+211 - South Sudan",
  "+239 - São Tomé and Príncipe",
  "+503 - El Salvador",
  "+1-721 - Sint Maarten",
  "+963 - Syria",
  "+268 - Eswatini",
  "+1-649 - Turks and Caicos Islands",
  "+235 - Chad",
  "+262 - French Southern Territories",
  "+228 - Togo",
  "+66 - Thailand",
  "+992 - Tajikistan",
  "+690 - Tokelau",
  "+670 - Timor-Leste",
  "+993 - Turkmenistan",
  "+216 - Tunisia",
  "+676 - Tonga",
  "+90 - Turkey",
  "+1-868 - Trinidad and Tobago",
  "+688 - Tuvalu",
  "+886 - Taiwan",
  "+255 - Tanzania",
  "+380 - Ukraine",
  "+256 - Uganda",
  "+1 - United States",
  "+598 - Uruguay",
  "+998 - Uzbekistan",
  "+379 - Vatican City",
  "+1-784 - Saint Vincent and the Grenadines",
  "+58 - Venezuela",
  "+1-284 - British Virgin Islands",
  "+1-340 - U.S. Virgin Islands",
  "+84 - Vietnam",
  "+678 - Vanuatu",
  "+681 - Wallis and Futuna",
  "+685 - Samoa",
  "+383 - Kosovo",
  "+967 - Yemen",
  "+262 - Mayotte",
  "+27 - South Africa",
  "+260 - Zambia",
  "+263 - Zimbabwe",
];

export const europeanCountries = [
  {
    sno: 1,
    countryName: "Albania",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{10}$",
    key2regex: "^[A-Za-z0-9]{10}$",
  },
  {
    sno: 2,
    countryName: "Andorra",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{8}$",
    key2regex: "^\\d{10}$",
  },
  {
    sno: 3,
    countryName: "Armenia",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^\\d{8}$",
    key2regex: "^\\d{8}$",
  },
  {
    sno: 4,
    countryName: "Austria",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{11}$",
    key2regex: "^[A-Za-z0-9]{9}$",
  },
  {
    sno: 5,
    countryName: "Azerbaijan",
    key1: "VAT Registration Number",
    key2: "Taxpayer Identification Number (TIN)/ Business registration Number",
    key1regex: "^\\d{10}$",
    key2regex: "^.*$",
  },
  {
    sno: 6,
    countryName: "Belarus",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^\\d{9}$",
    key2regex: "^\\d{9}$",
  },
  {
    sno: 7,
    countryName: "Belgium",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{12}$",
    key2regex: "^\\d{10}$",
  },
  {
    sno: 8,
    countryName: "Bosnia and Herzegovina",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^\\d{9}$",
    key2regex: "^\\d{7,10}$",
  },
  {
    sno: 9,
    countryName: "Bulgaria",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{11,12}$",
    key2regex: "^\\d{9}$",
  },
  {
    sno: 10,
    countryName: "Croatia",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{13}$",
    key2regex: "^\\d{11}$",
  },
  {
    sno: 11,
    countryName: "Cyprus",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{11}$",
    key2regex: "^[A-Za-z0-9]{8}$",
  },
  // country not found Czechia
  {
    sno: 12,
    countryName: "Czechia",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{10,12}$",
    key2regex: "^\\d{8}$",
  },
  {
    sno: 13,
    countryName: "Denmark",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{10}$",
    key2regex: "^\\d{8}$",
  },
  {
    sno: 14,
    countryName: "Estonia",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{11}$",
    key2regex: "^\\d{8}$",
  },
  {
    sno: 15,
    countryName: "Finland",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{10}$",
    key2regex: "^\\d{8}$",
  },
  {
    sno: 16,
    countryName: "France",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{13}$",
    key2regex: "^\\d{9}$",
  },
  {
    sno: 17,
    countryName: "Georgia",
    key1: "VAT Registration Number",
    key2: "Company Registration Certificate",
    key1regex: "^\\d{9}$",
    key2regex: "^\\d{9}$",
  },
  {
    sno: 18,
    countryName: "Germany",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{11}$",
    key2regex: "^[A-Za-z0-9]{8}$",
  },
  {
    sno: 19,
    countryName: "Greece",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{11}$",
    key2regex: "^\\d{9}$",
  },
  {
    sno: 20,
    countryName: "Hungary",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{10}$",
    key2regex: "^\\d+-\\d+$",
  },
  {
    sno: 21,
    countryName: "Iceland",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^\\d{10}$",
    key2regex: "^\\d{10}$",
  },
  {
    sno: 22,
    countryName: "Ireland",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{10}$",
    key2regex: "^[A-Za-z0-9]{8}$",
  },
  {
    sno: 23,
    countryName: "Italy",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{13}$",
    key2regex: "^[A-Za-z0-9]{9}$",
  },
  {
    sno: 24,
    countryName: "Kazakhstan",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^\\d{12}$",
    key2regex: "^\\d{12}$",
  },
  {
    sno: 25,
    countryName: "Kosovo",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^\\d{9}$",
    key2regex: "^\\d{9}$",
  },
  {
    sno: 26,
    countryName: "Latvia",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{13}$",
    key2regex: "^\\d{11}$",
  },
  {
    sno: 27,
    countryName: "Liechtenstein",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{16}$",
    key2regex: "^[A-Za-z0-9]{13}$",
  },
  {
    sno: 28,
    countryName: "Lithuania",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{11,14}$",
    key2regex: "^\\d{9}$",
  },
  {
    sno: 29,
    countryName: "Luxembourg",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{10}$",
    key2regex: "^[A-Za-z0-9]{7}$",
  },
  {
    sno: 30,
    countryName: "Malta",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{10}$",
    key2regex: "^[A-Za-z0-9]{6}$",
  },
  {
    sno: 31,
    countryName: "Moldova",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^\\d{7}$",
    key2regex: "^\\d{13}$",
  },
  {
    sno: 32,
    countryName: "Monaco",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{13}$",
    key2regex: "^[A-Za-z0-9]{8}$",
  },
  {
    sno: 33,
    countryName: "Montenegro",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^\\d{8}$",
    key2regex: "^\\d{8}$",
  },
  {
    sno: 34,
    countryName: "Netherlands",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{14}$",
    key2regex: "^\\d{8}$",
  },
  {
    sno: 35,
    countryName: "North Macedonia",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{15}$",
    key2regex: "^\\d{13}$",
  },
  {
    sno: 36,
    countryName: "Norway",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{14}$",
    key2regex: "^\\d{9}$",
  },
  {
    sno: 37,
    countryName: "Poland",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{12}$",
    key2regex: "^\\d{9}$",
  },
  {
    sno: 38,
    countryName: "Portugal",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{11}$",
    key2regex: "^\\d{9}$",
  },
  {
    sno: 39,
    countryName: "Romania",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{12}$",
    key2regex: "^(\\d{8}|[A-Za-z0-9]{10})$",
  },
  {
    sno: 40,
    countryName: "San Marino",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{7}$",
    key2regex: "^[A-Za-z0-9]{7}$",
  },
  {
    sno: 41,
    countryName: "Serbia",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^\\d{9}$",
    key2regex: "^\\d{8}$",
  },
  {
    sno: 42,
    countryName: "Slovakia",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{12}$",
    key2regex: "^\\d{8}$",
  },
  {
    sno: 43,
    countryName: "Slovenia",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{10}$",
    key2regex: "^\\d{8}$",
  },
  {
    sno: 44,
    countryName: "Spain",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{11}$",
    key2regex: "^[A-Za-z0-9]{9}$",
  },
  {
    sno: 45,
    countryName: "Sweden",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{14}$",
    key2regex: "^\\d{10}$",
  },
  {
    sno: 46,
    countryName: "Switzerland",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{16}$",
    key2regex: "^[A-Za-z0-9]{12}$",
  },
  {
    sno: 47,
    countryName: "Turkey",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^\\d{10}$",
    key2regex: "^(\\d{10}|\\d{16})$",
  },
  {
    sno: 48,
    countryName: "United Kingdom",
    key1: "VAT Registration Number",
    key2: "Company Registration Number",
    key1regex: "^[A-Za-z0-9]{11}$",
    key2regex: "^\\d{8}$",
  },

  // we need to update here regex
  [
    {
      sno: 49,
      countryName: "Bangladesh",
      key1: "VAT Registration Number",
      key2: "Certificate of Incorporation",
      key1regex: "^\\d{9}-\\d{4}$", // Example: 123456789-0123
      key2regex: "^[A-Za-z0-9]{10}$",
    },
    {
      sno: 50,
      countryName: "Sri Lanka",
      key1: "VAT Registration Number",
      key2: "Certificate of Incorporation",
      key1regex: "^\\d{12}$",
      key2regex: "^[A-Za-z0-9]{8}$",
    },
    {
      sno: 51,
      countryName: "Nepal",
      key1: "VAT Registration Number",
      key2: "Certificate of Incorporation",
      key1regex: "^\\d{9}$",
      key2regex: "^[A-Za-z0-9]{13}$",
    },
    {
      sno: 52,
      countryName: "Bhutan",
      key1: "VAT Registration Number",
      key2: "Certificate of Incorporation",
      key1regex: "^[A-Za-z0-9]{8}$",
      key2regex: "^[A-Za-z0-9]{16}$",
    },
    {
      sno: 53,
      countryName: "Singapore",
      key1: "Goods and Services Tax (GST) Registration Number",
      key2: "Unique Entity Number (UEN)",
      key1regex: "^\\d{10}$",
      key2regex: "^[A-Za-z0-9]{10}$",
    },
    {
      sno: 54,
      countryName: "Malaysia",
      key1: "Sales and Service Tax (SST)",
      key2: "Company Registration Number",
      key1regex: "^[A-Za-z0-9]{15}$",
      key2regex: "^[A-Za-z0-9]{12}$",
    },
    {
      sno: 55,
      countryName: "Indonesia",
      key1: "Taxpayer Identification Number (NPWP)",
      key2: "Company Registration Number (NIB)",
      key1regex: "^\\d{15}$",
      key2regex: "^\\d{13}$",
    },
    {
      sno: 56,
      countryName: "Taiwan",
      key1: "VAT Registration Number",
      key2: "Unified Business Number (UBN)",
      key1regex: "^\\d{8}$",
      key2regex: "^\\d{8}$",
    },
    {
      sno: 57,
      countryName: "Philippines",
      key2: "Certificate of Incorporation",
      key1: "Tax Identification Number (TIN)",
      key1regex: "^(CS|CN|OPC|LLP|FN)[0-9]{4}-?[0-9]{5}$",
      key2regex: "^\\d{12}$",
    },
    {
      sno: 58,
      countryName: "Brunei",
      key1: "Tax Identification Number (TIN)",
      key2: "Company Registration Number",
      key1regex: "^\\d{10}$",
      key2regex: "^(RC|BN|RFC)[0-9]{4}[0-9]{5}$",
    },
    {
      sno: 59,
      countryName: "Hong Kong",
      key1: "Business Registration Number/ Taxpayer Identification Number (TIN)",
      key2: "Company Registration Number",
      key1regex: "^\\d{8}$",
      key2regex: "^\\d{7}$",
    },
    {
      sno: 60,
      countryName: "Vietnam",
      key1: "Tax Code Number/ VAT Registration Number",
      key2: "Company Registration Certificate",
      key1regex: "^\\d{10}$",
      key2regex: "^\\d{10}$",
    },
    {
      sno: 61,
      countryName: "Thailand",
      key1: "Taxpayer Identification Number (TIN)/ VAT Number",
      key2: "Company Registration Number",
      key1regex: "^\\d{13}$",
      key2regex: "^\\d{13}$",
    },
    {
      sno: 62,
      countryName: "New Zealand",
      key1: "Goods and Services Tax (GST) Registration Number",
      key2: "Certificate of Incorporation",
      key1regex: "^\\d{9}$",
      key2regex: "^\\d{13}$",
    },
    {
      sno: 63,
      countryName: "Australia",
      key1: "Goods and Services Tax (GST) Registration Number",
      key2: "Australian Business Number (ABN)",
      key1regex: "^\\d{11}$",
      key2regex: "^\\d{11}$",
    },
    {
      sno: 64,
      countryName: "United Arab Emirates",
      key1: "VAT/TRN Registration Number",
      key2: "Emirates Id",
      key1regex: "^\\d{15}$",
      key2regex: "^[A-Za-z0-9]{15}$",
    },
    {
      sno: 65,
      countryName: "Oman",
      key1: "Tax Identification Number (TIN)",
      key2: "Commercial Registration Number (CRN)",
      key1regex: "^\\d{10}$",
      key2regex: "^\\d{1,10}$",
    },
    {
      sno: 66,
      countryName: "Saudi Arabia",
      key1: "Tax Identification Number (TIN)",
      key2: "Commercial Registration Number (CRN)",
      key1regex: "^\\d{15}$",
      key2regex: "^\\d{10}$",
    },
    {
      sno: 67,
      countryName: "Qatar",
      key1: "VAT Registration Number",
      key2: "Commercial Registration Number (CRN)",
      key1regex: "^\\d{15}$",
      key2regex: "^\\d{10}$",
    },
    {
      sno: 69,
      countryName: "Kuwait",
      key1: "Tax Identification Number (TIN)",
      key2: "Commercial Registration Number (CRN)",
      key1regex: "^\\d{9}$",
      key2regex: "^\\d{7}$",
    },
    {
      sno: 70,
      countryName: "Bahrain",
      key1: "Tax Identification Number (TIN)",
      key2: "Commercial Registration Number (CRN)",
      key1regex: "^\\d{9}$",
      key2regex: "^\\d{7}$",
    },
    {
      sno: 71,
      countryName: "Jordan",
      key1: "Taxpayer Identification Number (TIN)",
      key2: "Company Registration Number",
      key1regex: "^\\d{9}$",
      key2regex: "^\\d{7}$",
    },
    {
      sno: 72,
      countryName: "Egypt",
      key1: "Taxpayer Identification Number (TIN)",
      key2: "Commercial Registration Number",
      key1regex: "^\\d{9}(\\d{5})?$",
      key2regex: "^\\d{7}$",
    },
    {
      sno: 73,
      countryName: "Israel",
      key1: "Taxpayer Identification Number (TIN)/ VAT Registration Number",
      key2: "Company Registration Number",
      key1regex: "^\\d{9}$",
      key2regex: "^\\d{9}$",
    },

    {
      sno: 76,
      countryName: "Ukraine",
      key1: "Taxpayer Identification Number (TIN)",
      key2: "Certificate of Incorporation",
      key1regex: "^\\d{10}$",
      key2regex: "^\\d{8,10}$",
    },
    {
      sno: 77,
      countryName: "Russia",
      key1: "Taxpayer Identification Number (TIN)",
      key2: "Certificate of Incorporation",
      key1regex: "^\\d{10,12}$",
      key2regex: "^\\d{13}$",
    },
    {
      sno: 78,
      countryName: "United States",
      key1: "Sales Tax License ",
      key2: "Certificate of Incorporation",
      key1regex: "^\\d{9}$",
      key2regex: "^[A-Za-z0-9]{6,12}$",
    },
    {
      sno: 79,
      countryName: "Canada",
      key1: "Goods and Services Tax (GST)/Harmonized Sales Tax (HST) Number",
      key2: "Business Number (BN)",
      key1regex: "^[A-Za-z0-9]{15}$",
      key2regex: "^\\d{9,12}$",
    },
  ],
];
